name: fbls_env
channels:
  - numba
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio=4.0.0
  - appnope=0.1.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - astropy=5.3.3
  - astroquery=0.4.6
  - asttokens=2.4.0
  - async-lru=2.0.4
  - attrs=23.1.0
  - autograd=1.6.2
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=6.0.0
  - bokeh=2.4.3
  - brotli=1.0.9
  - brotli-python=1.0.9
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - colorama=0.4.6
  - comm=0.1.4
  - cycler=0.11.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - fbpca=1.0
  - fonttools=4.42.1
  - fqdn=1.5.1
  - freetype=2.10.4
  - future=0.18.3
  - giflib=5.2.1
  - html5lib=1.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - ipykernel=5.5.5
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jaraco.classes=3.3.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.19.1
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - jupyter_events=0.7.0
  - jupyter_server=2.7.3
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.6
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.0
  - jupyterlab_widgets=3.0.9
  - keyring=24.2.0
  - kiwisolver=1.4.4
  - lcms2=2.15
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.24
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lightkurve=2.4.1
  - llvm-openmp=16.0.6
  - llvmlite=0.41.0rc1
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - memoization=0.4.0
  - mistune=3.0.1
  - more-itertools=10.1.0
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert-core=7.8.0
  - nbformat=5.9.2
  - ncurses=6.4
  - notebook-shim=0.2.3
  - numba=0.58.0rc2
  - numpy=1.23.5
  - oktopus=0.1.2
  - openssl=3.1.3
  - overrides=7.4.0
  - packaging=23.1
  - pandas=2.0.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyerfa=2.0.0.3
  - pygments=2.16.1
  - pyobjc-core=9.2
  - pyobjc-framework-cocoa=9.2
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3.post1
  - pyvo=1.4.2
  - pyyaml=6.0.1
  - pyzmq=24.0.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.3
  - scikit-learn=1.2.2
  - scipy=1.11.1
  - send2trash=1.8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.6.2
  - terminado=0.17.1
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.10.0
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - uncertainties=3.1.7
  - unicodedata2=15.0.0
  - uri-template=1.3.0
  - urllib3=2.0.5
  - wcwidth=0.2.6
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.3
  - wheel=0.38.4
  - widgetsnbextension=4.0.9
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
